### ISSUE TITLE
320 samples for 16KHz speech

### ISSUE THREAD

**Issue by huhuqwaszxedc** [bingo-todd/Gammatone-filters#1]
Hello, which paper is your algorithm based on? I want to do a filter transformation with 320 samples of frame length, but it often fails to achieve good results

**Comment by bingo-todd** [comment]
The algorithm is mainly based on a paper published in 1991 which can find in  [here](https://www.phon.ucl.ac.uk/home/shl5/Darling1991-GammatoneFilter.pdf). 

what do you mean by "good results"? Can you describe you problems more specificly?  I just tried to filter a speech segment of 320 samples, results seem to be fine
`python
gt_filter = GTF(fs, freq_low=50, freq_high=5e3, n_band=4)
wav = wav[8000:8320]
wav_bands = gt_filter.filter(wav, norm_gain=True)
`
![test2](https://user-images.githubusercontent.com/40618142/192146232-d7f8681e-1945-4d27-89ef-42513e3afb8f.png)

**Comment by huhuqwaszxedc** [comment]
Thank you for your reply. My problem is that I want to implement an analysis synthesis process. But now, it is difficult to keep the same amplitude value in the sub-band of the low-frequency part. The reason I analyzed is that the impulse response of the low-frequency sub band was cut off in advance by 320 sample points, resulting in energy loss.

![Figure_1](https://user-images.githubusercontent.com/43325563/192214407-967558e0-d979-44ed-8573-2b0fcc42dbcc.png)
ng in energy loss.
![Figure_2](https://user-images.githubusercontent.com/43325563/192214413-9a24ca86-dd06-403d-8c02-0eb42ac2b700.png)
first picture is impulse response of the band 0，second pic is all 40 band from 80Hz to 8000Hz

**Comment by bingo-todd** [comment]
I think you are right. Maybe you should try Mel filterbanks which can be implemented based on FFT

**Comment by huhuqwaszxedc** [comment]
thanks，i will try,and i have last question.
What are the parameters for FIR and IIR filtering? I didn't introduce it from the 1991 article?
![新建位图图像](https://user-images.githubusercontent.com/43325563/192672289-898a5f1e-c548-4007-abfb-2c63f7b418d1.png)

**Comment by bingo-todd** [comment]
The artical only provide a basic idea that Gammatone can be viewed as a frequency-shifted low-pass filter.  The tranfer function of the low-pass filter can be formulated as 
![Screenshot 2022-09-29 231640](https://user-images.githubusercontent.com/40618142/193071114-de61670d-6c00-45ac-a93b-a0076423a1be.png)
I divided it into IIR part and FIR parts. The derivation process can be found [here](https://bingo-todd.github.io/work/2019/09/27/gtf_baseband_implementation.html)（It is writen in Chinese, but most of it are equations）
